title: <h2>Reza Nejad</h2> <p><h4> ICT System Engineer</h4></p>
logo: /Asset/images/Screenshot 2025-01-19 141808.png
description:  Microsoft Certified in Azure AI, CyberSecurity and IT Specialist in Python

theme: jekyll-theme-Minimal
