title: <h3>Reza Nejad</h3> <p><h5> ICT System Engineer</h5></p>
logo: /Asset/images/Screenshot 2025-01-19 141808.png
description: <h5> Microsoft Certified in Azure AI & IT Specialist in Python</h5>

theme: jekyll-theme-Minimal
