title: Reza Nejad <p> ICT System Engineer</p>
logo: /Asset/images/Screenshot 2025-01-19 141808.png
description:  Microsoft Certified in Azure AI, CyberSecurity and IT Specialist in Python

theme: jekyll-theme-Minimal
