title:    Reza Nejad  Microsoft Solution Associate
description: 
logo: /Asset/images/Screenshot 2025-01-19 141808.png
description:  Microsoft Certified Azure AI Fundamentals, Security, compliance and identity and IT Specialist in Python
theme: jekyll-theme-Minimal
