title:    Reza Nejad
logo: /Asset/images/Screenshot 2025-01-19 141808.png
description: MCP, MCTS, MCITP, MCSE, MCSolution Associate, Microsoft Certified Azure AI Fundamentals, Security, compliance and identity and IT Specialist in Python, 
#show_downloads: true
theme: jekyll-theme-Minimal
