title:    Reza Nejad Microsoft System Engineer in ICT
logo: /Asset/images/Screenshot 2025-01-19 141808.png
description:  Microsoft Certified Azure AI, CyberSecurity, compliance, identity and IT Specialist in Python
theme: jekyll-theme-Minimal
