title: <h3>Reza Kochesfehani</h3> <p><h5> ICT System Engineer</h5></p>
logo: /Asset/images/Screenshot 2025-01-19 141808.png
description: <h8> Microsoft Certified in Azure AI & IT Specialist in Python</h8>

theme: jekyll-theme-minimal


